18 sprint
alk8/PlaylistMaker pull request #19
Opened 2023-07-04 15:21 UTC by alk8

2023-07-04 18:47 UTC, NoDopezzz requested changes

2023-07-04 18:47 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/domain/models/states/StateMediatekaFragment.kt
> +enum class StateMediatekaFragment {
⏫ В данном случае стейт экрана относится к фрагменту, поэтому его стоит держать не в `domain` слое, а в `presentation`

2023-07-04 18:47 UTC, kirillNay commented on app/src/main/java/com/example/playlistmaker/presentation/fragments/EmptyMediatekaFragment.kt
> +class EmptyMediatekaFragment(private val state: StateMediatekaFragment) : Fragment() {
⚠️ Обрати внимание, что в конструктор передавать аргументы для фрагменты нельзя. Дело в том, что пересоздании `Activity` фргаменты, которые до этого также находились на экране будут создаваться внутри `Factory` с помощью `FragmentManager`, которые будут использовать создание класса фрагмента с пустым конструктором. Но `FragmentManager` с сможет найти такой констурктор, т.к. мы ожидаем аргумент `state`, поэтому случится краш.

2023-07-04 18:47 UTC, kirillNay commented on app/src/main/res/layout/activity_mediateka.xml
> +    <LinearLayout
💡 Стоит помнить, что лишняя вложенность при построении макетов [отрицательно сказывается](https://developer.android.com/topic/performance/rendering/optimizing-view-hierarchies#removing) на скорости отрисовки экрана, а значит и на производительности. Стоит всегда стараться делать верстку максимально плоской для лучшей производительности.

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/presentation/fragments/EmptyMediatekaFragment.kt
> +    private var _binding: FragmentEmptyMediatekaBinding? = null
⏫  При использовании ViewBinding во Fragment’ах [очень важно](https://developer.android.com/topic/libraries/view-binding#fragments) обнулять его при onDestroyView, т.к. можно вызвать утечку памяти.

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/values-en-rIE/strings.xml
> +    <string name="newPlaylist">New playlist</string>
Обрати внимание, что данный файл локализуется для ирландского английского (не знаю, это случайность или нет))

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/layout/fragment_empty_mediateka.xml
> +        android:layout_marginTop="15dp"
⏫ Согласно макетам отступы от таба составляют не `15dp`, а `24dp`

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/layout/fragment_empty_mediateka.xml
> +        app:layout_constraintHorizontal_bias="0.498"
⏫ Значение `layout_constraintHorizontal_bias` в этом случае по умолчанию будет и так равно 0.5, поэтому вручную нам его задавать необязательно. 
В случае вертикальных constraint'ов, привязка к нижнему краю экрана совсем необязательна и мы можем просто обойтись одной строчкой 
```kotlin
 app:layout_constraintTop_toBottomOf="@+id/newPlaylist"
```

Тогда и устанавливать `layout_constraintVertical_bias` не придется

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/layout/fragment_empty_mediateka.xml
> +        app:layout_constraintHorizontal_bias="0.497"
⏫ Комментарии по поводу `bias` также подходят и для этого элемента

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/presentation/fragments/EmptyMediatekaFragment.kt
> +class EmptyMediatekaFragment(private val state: StateMediatekaFragment) : Fragment() {
Ты можешь это проверить, если зайдешь на экран медиатеки и вызовешь смену конфигурации  - например смена шрифта, смена темы на темную или просто переворот экрана. Также такое может произойти, если ты свернешь приложение и долго не будешь в него заходить. Тогда Android вытеснет процесс твоего приложения, и когда ты вернешься обратно, то словишь ошибку:

```kotlin
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.example.playlistmaker.presentation.fragments.EmptyMediatekaFragment: could not find Fragment constructor
```

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/presentation/fragments/EmptyMediatekaFragment.kt
> +class EmptyMediatekaFragment(private val state: StateMediatekaFragment) : Fragment() {
Вообще, я бы тебе посоветовал разделить данные фрагменты на два разных. Понятно, что сейчас в этом нет смысла, т.к. их пустой стейт очень похож. Но в дальнейшем, когда логика нашего приложения будет усложняться нам придется разделить эти экраны

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/presentation/fragments/EmptyMediatekaFragment.kt
> +class EmptyMediatekaFragment(private val state: StateMediatekaFragment) : Fragment() {
[Здесь](https://stackoverflow.com/a/17436739) можно почитать о том, как правильно можно передавать аргументы между фрагментами

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/layout/fragment_empty_mediateka.xml
> +        android:id="@+id/imageView"
⚠️ Обрати внимание, что отступ между табом и плейсхолдером должен быть равен `106dp`.

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/layout/fragment_empty_mediateka.xml
> +        android:textSize="14sp"
⚠️ Текст кнопки не должен быть весь с большой буквы. Это стандартное поведение элемента `Button` можно исправить с помощью атрибута `android:textAllCaps="false"`

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/layout/activity_mediateka.xml
> +            android:layout_width="24dp"
⚠️ Судя по макетам размер кнопки соответствует `16dp x 16dp`

<img width="190" alt="image" src="https://github.com/alk8/PlaylistMaker/assets/56832972/2ffb00f2-b8b3-40c2-9c6e-f2159efc05e2">

2023-07-04 18:47 UTC, NoDopezzz commented on app/src/main/res/layout/activity_mediateka.xml
> +            android:id="@+id/tabLayout"
⚠️ Обрати внимание на стиль табов. 
Для изменения
 - цвета текста таба отвечает атрибут `tabTextColor`
 - цвета индикатора отвечает атрибут `tabIndicatorColor`

Но чтобы установить стиль текста нам стоит определить новый стиль в ресурсах и передать его в атрибут `tabTextAppearance`

<img width="558" alt="image" src="https://github.com/alk8/PlaylistMaker/assets/56832972/1f721c85-e462-44d0-89ed-05293b261d5f">

<img width="308" alt="Снимок экрана 2023-07-04 в 21 46 50" src="https://github.com/alk8/PlaylistMaker/assets/56832972/e3f089f2-ef8d-4fb9-9d1e-f45f3a981df7">

2023-07-05 08:46 UTC, alk8 commented on app/src/main/res/layout/activity_mediateka.xml
> +            android:id="@+id/tabLayout"
https://github.com/alk8/PlaylistMaker/assets/110226332/75ae58db-4422-4a23-8d9d-51f7452303bc

2023-07-05 14:11 UTC, NoDopezzz approved these changes

2023-07-05 14:11 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmaker/presentation/fragments/EmptyMediatekaFragment.kt
> +            STATE = state
⏫ Обрати внимание, что при пересоздании фрагмента поле STATE удалится и фрагмент воссоздастся с значением `STATE` по-умолчнию. Ты можешь это проверить следующим образом:
1. Перейти на экран медиатеки
2. Свернуть приложение и изменить тему на темную в настройках устройства
3. Вернуться к приложению и увидеть, что состояние экрана сбросилось и мы находимся на пустом экране.

Чтобы такое избежать мы можем реализовать сохранение стейта через `Bundle` так, как мы делали это в 9 спринте при сохранении ввода в поле поиска

2023-07-06 05:12 UTC, merged